// import Header from "../components/Header";
// import Footer from "../components/Footer";
// import { treeData } from "../lib/treeData";
// import { ClientProvider } from "../context/ClientProvider";
// import ConditionalHeader from "../components/ConditionalHeader";

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ClientProvider tree={treeData}>
//          <ConditionalHeader /> 
//           <main className="flex-grow">{children}</main>
//           <Footer />
//         </ClientProvider>
//       </body>
//     </html>
//   );
// }


import Footer from "../components/HomeFooter";
import { treeData } from "../lib/treeData";
import { ClientProvider } from "../context/ClientProvider";
import ConditionalHeader from "../components/ConditionalHeader";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Winterbeast",
  description: "Recording studio in Portland focused on album production and long-form collaboration.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="antialiased bg-[#181818] text-[#e6e6e6]">
        <ClientProvider tree={treeData}>
          <ConditionalHeader />
          <main className="flex-grow">{children}</main>
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}