export const homePageImages = [
  // "/images/home-page/02-2.webp",
  // "/images/home-page/02.webp",
  // "/images/home-page/02a.webp",
  // "/images/home-page/09a-2.webp",
  // "/images/home-page/03 copy.webp",
  // "/images/home-page/03-2.webp",
  // "/images/home-page/09a.webp",
  // "/images/home-page/35a wb control.webp",
  // "/images/home-page/03.webp",
  // "/images/home-page/04.webp",
  // "/images/home-page/05 copy.webp",
  // "/images/home-page/05.webp",
  // "/images/home-page/05a.webp",
  // "/images/home-page/14a.webp",
  // "/images/home-page/06.webp",
  // "/images/home-page/07.webp",
  // "/images/home-page/08.webp",
  // "/images/home-page/09-2.webp",
  // "/images/home-page/10-2.webp",
  // "/images/home-page/10A.webp",
  // "/images/home-page/11.webp",
  // "/images/home-page/11a-2.webp",
  // "/images/home-page/12.webp",
  // "/images/home-page/12a.webp",
  // "/images/home-page/13a.webp",
  // "/images/home-page/18a.webp",
  // "/images/home-page/20a-2.webp",
  // "/images/home-page/20a.webp",
  // "/images/home-page/21-2.webp",
  // "/images/home-page/21.webp",
  // "/images/home-page/21a.webp",
  // "/images/home-page/22a.webp",
  // "/images/home-page/28a-2.webp",
  // "/images/home-page/23A.webp",
  // "/images/home-page/28a.webp",
  // "/images/home-page/29a.webp",
  // "/images/home-page/refrigerated nurses homepage.webp",
  // "/images/home-page/31a.webp",
  // "/images/home-page/35a.webp",
  // "/images/home-page/WB_Hail_15a.webp",
  // "/images/home-page/WB_Hail_21a.webp",
  // "/images/home-page/WB_Hail_24a.webp",
  // "/images/home-page/WB_Hail_28a.webp",
];
