import { GalleryImage } from "./types/artist";
import { idIncrement } from "@/utils/id-increment";

export const homePageGalleryImageData: GalleryImage[] = [
  {
    url: "/images/home-page/brian-knife-slide-lacephale.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Knife slides on guitar strings",
  },
  {
    url: "/images/home-page/paul-bass-synth-dubs-lacephale.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Bass + Synth dubs",
  },
  {
    url: "/images/home-page/nikhil-synth-interludes-hollow-senses.webp",
    project: "Hollow Senses",
    date: "2023",
    priority: idIncrement(),
    description: "Synth interlude tracking",
  },
  {
    url: "/images/home-page/ursula-live-drums-notnauts.webp",
    project: "Notnauts",
    date: "2023",
    priority: idIncrement(),
    description: "Live drum tracking",
  },
  {
    url: "/images/home-page/sean-screaming-the-mistons.webp",
    project: "The Mistons",
    date: "2023",
    priority: idIncrement(),
    description: "Full pass vocal takes",
  },
  {
    url: "/images/home-page/danny-working-on-bass-parts-lacephale.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Honing bass parts during tracking",
  },
   {
    url: "/images/home-page/mic-collection-studio.webp",
    project: "Studio",
    date: "2023",
    priority: idIncrement(),
    description: "Mic lockerless",
  },
   {
    url: "/images/home-page/control-room-studio.webp",
    project: "Studio",
    date: "2023",
    priority: idIncrement(),
    description: "Control Room",
  },
   {
    url: "/images/home-page/brian-guitar-doubling-lacephale.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
   {
    url: "public/images/home-page/liz-vocals-lacephale.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Vocal tracking",
  },
  {
    url: "/images/home-page/drums-micd-up-zothique.webp",
    project: "Zothique",
    date: "2023",
    priority: idIncrement(),
    description: "Drums mic'd up",
  },
  {
    url: "/images/home-page/christine-key-dubs-otd.webp",
    project: "Old Town Diamonds",
    date: "2023",
    priority: idIncrement(),
    description: "Finishing touches with key dubs",
  },
  {
    url: "/images/home-page/knock-knock-jokes-listening-back-otd.webp",
    project: "Old Town Diamonds",
    date: "2023",
    priority: idIncrement(),
    description: "Inside jokes between listens",
  },
  {
    url: "/images/home-page/danny-mid-take-lacephale.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Danny locked in mid take",
  },
  {
    url: "/images/home-page/hiwatt-the-mistons.webp",
    project: "The Mistons",
    date: "2023",
    priority: idIncrement(),
    description: "A beautiful rig",
  },
  {
    url: "/images/home-page/brandon-practicing-between-takes-the-mistons.webp",
    project: "The Mistons",
    date: "2023",
    priority: idIncrement(),
    description: "Practicing between breaks",
  },
  {
    url: "/images/home-page/dean-warming-up-the-mistons.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Warming up before starting live tracking",
  },
  {
    url: "/images/home-page/brian-live-noise-tracking-hail.webp",
    project: "Hail",
    date: "2023",
    priority: idIncrement(),
    description: "Setting up for live band noise tracking",
  },
  {
    url: "/images/home-page/danny-bass-feedback-lacephale.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Bass feedback",
  },
  {
    url: "/images/home-page/sax-dubs-notnauts.webp",
    project: "Notnauts",
    date: "2023",
    priority: idIncrement(),
    description: "Layering sax through amps",
  },
  {
    url: "/images/home-page/lloyd-live-noise-tracking-hail.webp",
    project: "Hail",
    date: "2023",
    priority: idIncrement(),
    description: "Group noise tracking",
  },
  {
    url: "/images/home-page/brian-live-tracking-notnauts.webp",
    project: "Notnauts",
    date: "2023",
    priority: idIncrement(),
    description: "Discussing between takes",
  },
  {
    url: "public/images/home-page/ryan-setting-up-bass-dubs-entrain.webp",
    project: "Entrain",
    date: "2023",
    priority: idIncrement(),
    description: "Setting up for over dubbing bass tracks",
  },
  {
    url: "/images/home-page/12a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
  {
    url: "/images/home-page/13a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },


   {
    url: "/images/home-page/18a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
   {
    url: "/images/home-page/20a-2.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
   {
    url: "/images/home-page/20a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
   {
    url: "/images/home-page/21-2.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
   {
    url: "/images/home-page/21.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
   {
    url: "/images/home-page/21a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
   {
    url: "/images/home-page/22a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
   {
    url: "/images/home-page/28a-2.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
   {
    url: "/images/home-page/23A.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
   {
    url: "/images/home-page/28a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },


  {
    url: "/images/home-page/29a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
  {
    url: "/images/home-page/refrigerated nurses homepage.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
  {
    url: "/images/home-page/31a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
  {
    url: "/images/home-page/35a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
  {
    url: "/images/home-page/WB_Hail_15a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
  {
    url: "/images/home-page/WB_Hail_21a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
  {
    url: "/images/home-page/WB_Hail_24a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
  {
    url: "/images/home-page/WB_Hail_28a.webp",
    project: "L'Acephale",
    date: "2023",
    priority: idIncrement(),
    description: "Doubling guitars",
  },
];
